pipeline{
    agent any
    stages {
        stage('ip address') {
            steps {
                echo 'Getting IP address...'
                sh '''
                hostname -I
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
