pipeline {
    agent any

    stages {
        stage('CPU Info') {
            steps {
                echo 'Getting CPU info...'
                sh 'lscpu | grep "Model name"'
                sh 'nproc'
            }
        }

        stage('IP Address') {
            steps {
                echo 'Getting IP address...'
                sh 'hostname -I'
            }
        }

        stage('Memory Info') {
            steps {
                echo 'Getting memory info...'
                sh 'free -h'
            }
        }
    }
}
